import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import NavBar from '../components/NavBar'
import PopularClass from '../components/PopularClass'
import Services from '../components/Services'
import { getSession, useSession, signOut } from "next-auth/react"


export default function Home() {
  
  const { data: session } = useSession()
  
  return (
    <div >
      <Head>
        <title>Letaff -Circle Education Website</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Services/>
      <PopularClass/>
      <Footer/>
    </div>
  )
}
