import Head from 'next/head'
import Footer from '../components/landingpage/Footer'
import Hero from '../components/landingpage/Hero'
import PopularClass from '../components/landingpage/PopularClass'
import Services from '../components/landingpage/Services'
import { useContext } from 'react';
import {Context} from '../context';
import WelcomePage from '../components/welcome'



export default function Home() {
  const { state, dispatch } = useContext(Context);
  const {user} = state;

  
  return (
    <div >
      <Head>
        <title>Letaff Circle</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {user === null && (
        <>
          <Hero/>
          <Services/>
          <PopularClass/>
          <Footer/>
        </>
      )}
      
      {user !== null && (
        <>
          <WelcomePage/>
        </>
      )}
    </div>
  )
}
